### ISSUE TITLE
Error: please put HAR files in harPool directory!

### ISSUE THREAD

**Issue by haers** [maxduke/go-chatgpt-api#18]
今天中午发现不行了~老板

**Comment by maxduke** [comment]
HAR文件没放么？之前只用3.5？

**Comment by haers** [comment]
只用了3.5，accesstoken，从issue那里过来的用的您的方法，昨天开始不行了。就搁置了，有消息通知我哈，感谢！

**Comment by maxduke** [comment]
查看下你当前帐号3.5是不是也需要arkose token了，按以下方法获取
https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0

**Comment by haers** [comment]
这个最新的方法我试了下，不太会用，然后我就停止docker，更新您最新的镜像，然后重启就行了！感谢！
