### ISSUE TITLE
 Request failed: forbidden (403)

### ISSUE THREAD

**Issue by justincnn** [maxduke/go-chatgpt-api#19]
今天开始突然403了，
chatgpt3.5，

请大神指点下，谢谢

**Comment by maxduke** [comment]
今天好像看到很多都报403错误，但我这边3.5和4都正常……看看大佬怎么修复吧，等有方案我会尝试更新

**Comment by xionggd** [comment]
![111111111](https://github.com/maxduke/go-chatgpt-api/assets/30542155/e85c09c2-5aa9-4fcb-84dc-e1097c9e1700)
403 了

**Comment by maxduke** [comment]
都挂了，今早我的也挂了，等有解决方案了修

**Comment by xionggd** [comment]
好咯  只能这样了

**Comment by maxduke** [comment]
已修复，用最新的代码或者拉最新的docker image

**Comment by xionggd** [comment]
老哥 牛逼，可以用了。

**Comment by ZYMirror** [comment]
又突然403了，大佬
failed to start, please try again later: 403 Forbidden

**Comment by maxduke** [comment]
我这边试了正常。你看看是不是IP
黑了

**Comment by ZYMirror** [comment]
> 我这边试了正常。你看看是不是IP 黑了

代理的ip，还是我本地的ip？

**Comment by ZYMirror** [comment]
> 我这边试了正常。你看看是不是IP 黑了

好像是被cf盾了？？跟这个有没有关系，我打开openai的官网就会出现cf验证

**Comment by maxduke** [comment]
> > 我这边试了正常。你看看是不是IP 黑了
> 
> 好像是被cf盾了？？跟这个有没有关系，我打开openai的官网就会出现cf验证

有关系，那就是你部署的服务器的IP黑了

**Comment by ZYMirror** [comment]
> > > 我这边试了正常。你看看是不是IP 黑了
> > 
> > 
> > 好像是被cf盾了？？跟这个有没有关系，我打开openai的官网就会出现cf验证
> 
> 有关系，那就是你部署的服务器的IP黑了

那我换个代理试试，多谢大佬，大佬有没有群呀

**Comment by maxduke** [comment]
> > > > 我这边试了正常。你看看是不是IP 黑了
> > > 
> > > 
> > > 好像是被cf盾了？？跟这个有没有关系，我打开openai的官网就会出现cf验证
> > 
> > 
> > 有关系，那就是你部署的服务器的IP黑了
> 
> 那我换个代理试试，多谢大佬，大佬有没有群呀

最好是自己有干净点IP的服务器部署，量小的话比较稳定，代理什么的IP万人骑，很容易黑。 
没群。这个项目主要魔改自用的，以后出问题能修复就尽量修复，真没辙就不修了。
