### ISSUE TITLE
ERRO[0000] failed to start, please try again later: 403 Forbidden 

### ISSUE THREAD

**Issue by yg9538** [maxduke/go-chatgpt-api#21]
ERRO[0000] failed to start, please try again later: 403 Forbidden

**Comment by kingfer30** [comment]
CF拦截了, 可以在拦截那里加个逻辑吗? 接入第三方过CF的逻辑

**Comment by maxduke** [comment]
IP不干净或量太大。
这个项目主要是自用的，目前没计划对接CF过盾。

**Comment by yg9538** [comment]
感觉不太像，只要重启容器就会这样，谢谢大佬
