### ISSUE TITLE
当gpt-4次数用完时，返回429时，没有完整返回信息

### ISSUE THREAD

**Issue by 100skeep** [maxduke/go-chatgpt-api#24]

**Comment by 18230** [comment]
从103行开始加上图片代码
![Uploading Snipaste_2024-03-29_13-56-05.png…]()

**Comment by 18230** [comment]
103开始注释，可修改如下：
`	// 检查状态码是否大于299
	if resp.StatusCode > 299 {

		// 关闭响应体
		defer resp.Body.Close()

		// 设置响应头
		for name, values := range resp.Header {
			c.Writer.Header()[name] = values
		}
		c.Writer.WriteHeader(resp.StatusCode)

		// 直接转发响应体
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Printf("Could not read response body: %v\n", err)
			// 可能需要在这里处理错误
		} else {
			log.Printf("Request failed with status code: %d, status: %s, body: %s\n", resp.StatusCode, http.StatusText(resp.StatusCode), string(body))
		}

		c.Writer.Write(body)
		return nil, true
	}`

**Comment by 18230** [comment]
103开始注释，可修改如下：`	if resp.StatusCode > 299 {

		// 关闭响应体
		defer resp.Body.Close()

		// 设置响应头
		for name, values := range resp.Header {
			c.Writer.Header()[name] = values
		}
		c.Writer.WriteHeader(resp.StatusCode)

		// 直接转发响应体
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Printf("Could not read response body: %v\n", err)
			// 可能需要在这里处理错误
		} else {
			log.Printf("Request failed with status code: %d, status: %s, body: %s\n", resp.StatusCode, http.StatusText(resp.StatusCode), string(body))
		}

		c.Writer.Write(body)
		return nil, true
	}`

**Comment by 18230** [comment]
103开始注释，可修改如下：
`	if resp.StatusCode > 299 {

		// 关闭响应体
		defer resp.Body.Close()

		// 设置响应头
		for name, values := range resp.Header {
			c.Writer.Header()[name] = values
		}
		c.Writer.WriteHeader(resp.StatusCode)

		// 直接转发响应体
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Printf("Could not read response body: %v\n", err)
			// 可能需要在这里处理错误
		} else {
			log.Printf("Request failed with status code: %d, status: %s, body: %s\n", resp.StatusCode, http.StatusText(resp.StatusCode), string(body))
		}

		c.Writer.Write(body)
		return nil, true
	}`

**Comment by 18230** [comment]
103开始注释，可修改如下：

	if resp.StatusCode > 299 {

		// 关闭响应体
		defer resp.Body.Close()

		// 设置响应头
		for name, values := range resp.Header {
			c.Writer.Header()[name] = values
		}
		c.Writer.WriteHeader(resp.StatusCode)

		// 直接转发响应体
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Printf("Could not read response body: %v\n", err)
			// 可能需要在这里处理错误
		} else {
			log.Printf("Request failed with status code: %d, status: %s, body: %s\n", resp.StatusCode, http.StatusText(resp.StatusCode), string(body))
		}

		c.Writer.Write(body)
		return nil, true
	}

**Comment by maxduke** [comment]
> 103开始注释，可修改如下：
> 
> ```
> if resp.StatusCode > 299 {
> 
> 	// 关闭响应体
> 	defer resp.Body.Close()
> 
> 	// 设置响应头
> 	for name, values := range resp.Header {
> 		c.Writer.Header()[name] = values
> 	}
> 	c.Writer.WriteHeader(resp.StatusCode)
> 
> 	// 直接转发响应体
> 	body, err := io.ReadAll(resp.Body)
> 	if err != nil {
> 		log.Printf("Could not read response body: %v\n", err)
> 		// 可能需要在这里处理错误
> 	} else {
> 		log.Printf("Request failed with status code: %d, status: %s, body: %s\n", resp.StatusCode, http.StatusText(resp.StatusCode), string(body))
> 	}
> 
> 	c.Writer.Write(body)
> 	return nil, true
> }
> ```

欢迎PR

**Comment by 18230** [comment]
ok，已提交

**Comment by maxduke** [comment]
已由 https://github.com/18230 的
https://github.com/maxduke/go-chatgpt-api/pull/27
修复
