### ISSUE TITLE
项目支持自动更新token吗？

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [maxduke/go-chatgpt-api#31]
需要手动每隔一段时间重新编辑token吗？

**Comment by maxduke** [comment]
填refresh_token，每7天自动更新token，这个是对chat2api的

**Comment by danepoirier0** [comment]
这个refresh_token从哪获取?

**Comment by maxduke** [comment]
> 这个refresh_token从哪获取?

https://demo.xyhelper.cn/applelogin
xyhelper的免费服务，今晚会关闭。要获取的话乘早
