### ISSUE TITLE
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

### ISSUE THREAD

**Issue by xionggd** [maxduke/go-chatgpt-api#35]
老哥 这个问题咋回事 突然不行了。
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

日志：WARN[2054336] you have no permission to use this model

![gpt1](https://github.com/maxduke/go-chatgpt-api/assets/30542155/de89ab7d-f764-4b4b-8de8-857bb25d126b)
![gpt2](https://github.com/maxduke/go-chatgpt-api/assets/30542155/112379cb-23b1-4f86-b4fa-07000fe86412)

**Comment by haers** [comment]
+1

**Comment by xktder** [comment]
+1

**Comment by maxduke** [comment]
逆向被官方识别了，之后有空尝试修复

**Comment by xionggd** [comment]
@maxduke 期待大佬修复。

**Comment by maxduke** [comment]
已修复，拉最新代码或者镜像

**Comment by eureka6** [comment]
> 已修复，拉最新代码或者镜像

```
Attaching to goapi
goapi  | success read chat arkose
goapi  | success read chat arkose
goapi  | success read chat arkose
goapi  | INFO[0000] service go-chatgpt-api is ready
goapi  | [GIN] 2024/04/16 - 21:43:19 | 200 |  227.003525ms |   45.88.194.220 | GET      "/chatgpt/backend-api/accounts/check/v4-2023-04-27"
goapi  | [GIN] 2024/04/16 - 21:43:57 | 403 |  666.826458ms |   45.88.194.220 | POST     "/chatgpt/backend-api/conversation"
```
佬，拉的最新镜像，报403

**Comment by eureka6** [comment]
> 已修复，拉最新代码或者镜像

```
Attaching to goapi
goapi  | success read chat arkose
goapi  | success read chat arkose
goapi  | success read chat arkose
goapi  | INFO[0000] service go-chatgpt-api is ready
goapi  | [GIN] 2024/04/16 - 21:43:19 | 200 |  227.003525ms |   xx.xx.xxx.xx | GET      "/chatgpt/backend-api/accounts/check/v4-2023-04-27"
goapi  | [GIN] 2024/04/16 - 21:43:57 | 403 |  666.826458ms |   xx.xx.xxx.xx | POST     "/chatgpt/backend-api/conversation"
```

佬，拉的最新镜像，报403

**Comment by maxduke** [comment]
> > 已修复，拉最新代码或者镜像
> 
> ```
> Attaching to goapi
> goapi  | success read chat arkose
> goapi  | success read chat arkose
> goapi  | success read chat arkose
> goapi  | INFO[0000] service go-chatgpt-api is ready
> goapi  | [GIN] 2024/04/16 - 21:43:19 | 200 |  227.003525ms |   xx.xx.xxx.xx | GET      "/chatgpt/backend-api/accounts/check/v4-2023-04-27"
> goapi  | [GIN] 2024/04/16 - 21:43:57 | 403 |  666.826458ms |   xx.xx.xxx.xx | POST     "/chatgpt/backend-api/conversation"
> ```
> 
> 佬，拉的最新镜像，报403

再重新拉下

**Comment by xionggd** [comment]
@maxduke 已经可以了 感谢大佬。

**Comment by eureka6** [comment]
> > > 已修复，拉最新代码或者镜像
> > 
> > 
> > ```
> > Attaching to goapi
> > goapi  | success read chat arkose
> > goapi  | success read chat arkose
> > goapi  | success read chat arkose
> > goapi  | INFO[0000] service go-chatgpt-api is ready
> > goapi  | [GIN] 2024/04/16 - 21:43:19 | 200 |  227.003525ms |   xx.xx.xxx.xx | GET      "/chatgpt/backend-api/accounts/check/v4-2023-04-27"
> > goapi  | [GIN] 2024/04/16 - 21:43:57 | 403 |  666.826458ms |   xx.xx.xxx.xx | POST     "/chatgpt/backend-api/conversation"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 佬，拉的最新镜像，报403
> 
> 再重新拉下

可以了，感谢大佬！
