### ISSUE TITLE
docker镜像拉取不了

### ISSUE THREAD

**Issue by eureka6** [maxduke/go-chatgpt-api#38]
大佬，docker镜像拉取失败了。

```
~# docker pull ghcr.io/maxduke/go-chatgpt-api:latest
latest: Pulling from maxduke/go-chatgpt-api
manifest unknown
```
试了很多次都没成功。

而且20天前的那一版好像被openai识别了，已经用不了了。

**Comment by eureka6** [comment]
```
docker pull maxduke/go-chatgpt-api:latest
```
这个拉取成功

**Comment by yizhilangou** [comment]
> ```
> docker pull maxduke/go-chatgpt-api:latest
> ```
> 
> 这个拉取成功

正常运行吗

**Comment by maxduke** [comment]
加tag或者用docker hub的。 两边是同步的

**Comment by eureka6** [comment]
> > ```
> > docker pull maxduke/go-chatgpt-api:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个拉取成功
> 
> 正常运行吗

正常的
