### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by yizhilangou** [maxduke/go-chatgpt-api#39]
![image (6)](https://github.com/maxduke/go-chatgpt-api/assets/97778348/27194a7c-0c84-43a8-84fd-69ade18cc92b)
![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/cf3199eb-43b5-47e6-b9bf-6c513f1fffa7)
pull 的最新镜像
```
sudo docker run -d --name go-chatgpt-api \
	-p 127.0.0.1:8080:8080 \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-e TZ=Asia/Shanghai \
	-e PROXY= \
	-e ARKOSE_TOKEN_URL= \
	-e BX= \
	-e BX_URL= \
	-e OPENAI_EMAIL= \
	-e OPENAI_PASSWORD= \
	-e CONTINUE_SIGNAL= \
	--restart unless-stopped \
	maxduke/go-chatgpt-api
```

**Comment by maxduke** [comment]
docker配置问题，网络不通。关键地方你也打了马赛克，我也看不出。不要用127.0.0.1，建议网上查下docker 端口映射的相关配置。

**Comment by yizhilangou** [comment]
> docker配置问题，网络不通。关键地方你也打了马赛克，我也看不出。不要用127.0.0.1，建议网上查下docker 端口映射的相关配置。

![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/5d42155c-a038-400a-b6c3-0c12dc6e033d)
![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/e7f5cfa3-9028-4921-b9f2-e8619c52cc12)
```
sudo docker run -d --name go-chatgpt-api \
	-p 8080:8080 \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-e TZ=Asia/Shanghai \
	-e PROXY= \
	-e ARKOSE_TOKEN_URL= \
	-e BX= \
	-e BX_URL= \
	-e OPENAI_EMAIL= \
	-e OPENAI_PASSWORD= \
	-e CONTINUE_SIGNAL= \
	--restart unless-stopped \
	maxduke/go-chatgpt-api
```
找不到是啥问题，防火墙关了，docker也重启过

**Comment by maxduke** [comment]
172.208.90.170是什么地址？docker container的地址？ 看上去不通啊。 你cws和这个部署在一个机器上的话用127.0.0.1试试。而且你har也没映射。建议看下文档，或群里问问别人。

**Comment by yizhilangou** [comment]
服务器的IP地址，之前也是这样配置的。待会重装docker试试
