### ISSUE TITLE
failed to refresh PUID: Failed to get CSRF token.

### ISSUE THREAD

**Issue by xixi-furry** [maxduke/go-chatgpt-api#41]
配置的账号密码，不知道是ip有问题了还是咋的，提示429

**Comment by maxduke** [comment]
这个错误通常是ip黑了。
之前能用么？登录Har抓了么？我今天一个IP也被429了。。。

**Comment by xixi-furry** [comment]
之前可以，我用的easyvm的，那估计就是IP的问题了

**Comment by xixi-furry** [comment]
很奇怪，用的其他的脚本测试我的IP都可以完整解锁ChatGPT，网页+客户端，但是实际上就会提示这个。是我有啥参数没带对的么。

**Comment by maxduke** [comment]
> 很奇怪，用的其他的脚本测试我的IP都可以完整解锁ChatGPT，网页+客户端，但是实际上就会提示这个。是我有啥参数没带对的么。

我有个IP也这个情况，最近CF盾好像有点变化

**Comment by xixi-furry** [comment]
上proxy正常了，就是如果这个proxy能设置多个且轮训就好了

**Comment by maxduke** [comment]
有ipv6的可以用 https://github.com/gngpp/vproxy 轮询。
其它还有什么知道的，欢迎发在这。

**Comment by huchenz1** [comment]
我也是在docker compose里设置了本机的一个ipv6子网，现在也可以正常用了
