### ISSUE TITLE
Endpoint /chatgpt/login is invalid

### ISSUE THREAD

**Issue by wrhsd1** [maxduke/go-chatgpt-api#42]
The endpoint /chatgpt/login is invalid and currently returning an error with the message: 'missing access token'. Could you please take a look at it?

**Comment by maxduke** [comment]
前端用的哪个触发的这个endpoint?

**Comment by wrhsd1** [comment]
之前直接post用户名密码 会返回accessToken，现在返回的是 data: { errorMessage: 'missing access token' }

**Comment by maxduke** [comment]
登陆的Har配置了么？已经配了的话重新抓下。没配的话抓下配进去试试。登陆接口对服务器ip要求极高。有refrash token的话建议用那个

**Comment by wrhsd1** [comment]
好的 试了一下，网页访问好像是弹cf验证了，应该跟程序没关系
谢谢回复
