### ISSUE TITLE
请问arm64的版本还有在更新么么？

### ISSUE THREAD

**Issue by justincnn** [maxduke/go-chatgpt-api#48]
作者你好，今天我在pull 5月1号更新的时候，无法发现新的image，
请问下，arm64还是更新么？如果已经停更，是否可以同步更新，谢谢

![](https://s2.loli.net/2024/05/03/TDM3Oj5u9JziaVB.png)

**Comment by maxduke** [comment]
一直同步在更新，带上tag lastest试下

**Comment by justincnn** [comment]
> 一直同步在更新，带上tag lastest试下

已经加了latest了，还是pull不到

~~~yaml
services:
  go-chatgpt-api:
    image: maxduke/go-chatgpt-api:latest
    container_name: go-chatgpt-api
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
~~~

![](https://s2.loli.net/2024/05/03/WMG2JIKwybHtBs7.png)

**Comment by maxduke** [comment]
![image](https://github.com/maxduke/go-chatgpt-api/assets/440836/cbef20b0-e71b-4972-af00-79e1f3acb9c2)
看了下没问题
要不你看看本地image id，是不是已经最新了

**Comment by justincnn** [comment]
> ![image](https://private-user-images.githubusercontent.com/440836/327684268-cbef20b0-e71b-4972-af00-79e1f3acb9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Nzc4MzUsIm5iZiI6MTcxNDc3NzUzNSwicGF0aCI6Ii80NDA4MzYvMzI3Njg0MjY4LWNiZWYyMGIwLWU3MWItNDk3Mi1hZjAwLTc5ZTFmM2FjYjljMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QyMzA1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjUwOTFiYzBiMjJjY2EwYWM3M2JjZDczYmVhMmRlYjY2MjZkNDljNGI3NTE0ZmFhZGJmOWVlYjBlMmJlOGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c69WAMpttbxGagsypKAusN42KK44MEXIx_y0JHlctu0) 看了下没问题 要不你看看本地image id，是不是已经最新了

你好，image的id和你不一样

![](https://s2.loli.net/2024/05/04/c2vWXIVlsedj8nC.png)

**Comment by maxduke** [comment]
我错了，不能通过那个方法。目前由于官方域名变化，重启后应该都会报403错误，等我之后修复了看。一般都会拉到最新的

**Comment by maxduke** [comment]
今天又更新了一版，你可以比较下，前后的image id

**Comment by justincnn** [comment]
> 今天又更新了一版，你可以比较下，前后的image id

感谢，已经更新了，

![](https://s2.loli.net/2024/05/08/J1zMCxDmq8jTgYt.png)
