### ISSUE TITLE
  "error": "unable to create ws tunnel"

### ISSUE THREAD

**Issue by kylinpoet** [maxduke/go-chatgpt-api#52]
![image](https://github.com/maxduke/go-chatgpt-api/assets/6766883/ad32a660-976d-466f-9a6c-d89e74fea731)

请问下出现这个错误该如何解决？
另外 网址现在编程chatgpt.com，不能抓 har了。还需要上传吗？

**Comment by maxduke** [comment]
chat2api 建议用 https://github.com/xqdoo00o/ChatGPT-to-API 试试。
肯定需要上传。原有的不行就抓chatgpt.com上的har。
