### ISSUE TITLE
大佬 errorMessage	"please provide a valid access token or api key in 'Authorization' header"

### ISSUE THREAD

**Issue by yizhilangou** [maxduke/go-chatgpt-api#53]

**Comment by maxduke** [comment]
你怎么用的？说清楚才能帮你看啊

**Comment by yizhilangou** [comment]
> 你怎么用的？说清楚才能帮你看啊

正常运行的

**Comment by maxduke** [comment]
> > 你怎么用的？说清楚才能帮你看啊
> 
> 正常运行的

正常运行的log不会报这个错，触发了request才会报这个错。
请回答：
用什么客户端？
怎么配置的？
怎么操作的？
有没有request 的header和body？

**Comment by yizhilangou** [comment]
> > > 你怎么用的？说清楚才能帮你看啊
> > 
> > 
> > 正常运行的
> 
> 正常运行的log不会报这个错，触发了request才会报这个错。 请回答： 用什么客户端？ 怎么配置的？ 怎么操作的？ 有没有request 的header和body？

![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/9ab42599-98dd-4fe6-afd8-7d3ed3259f07)
```
sudo docker run -d --name go-chatgpt-api \
	-p 8080:8080 \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-e TZ=Asia/Shanghai \
	-e PROXY= \
	-e ARKOSE_TOKEN_URL= \
	-e BX= \
	-e BX_URL= \
	-e OPENAI_EMAIL= \
	-e OPENAI_PASSWORD= \
	-e CONTINUE_SIGNAL= \
	--restart unless-stopped \
	maxduke/go-chatgpt-api
```
http://ip:8080/chatgpt/backend-api/conversation
之后访问这个出现
![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/a5744cfa-0a6c-4965-a508-1fe7e5a5fca3)

![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/7bb6f605-da56-4193-bbc2-377012f2fd21)

**Comment by maxduke** [comment]
你header不放accessToken当然报错呀。。。

**Comment by yizhilangou** [comment]
> 你header不放accessToken当然报错呀。。。

意思是，套壳网站没有放accessToken，还是部署go-chatgpt-api需要加入accessToken

**Comment by maxduke** [comment]
哪个套壳网站？之前问你用的哪个前端，你就告诉我访问http://ip:8080/chatgpt/backend-api/conversation

**Comment by yizhilangou** [comment]
> 哪个套壳网站？之前问你用的哪个前端，你就告诉我访问http://ip:8080/chatgpt/backend-api/conversation
https://github.com/Chanzhaoyu/chatgpt-web 这个，抱歉大佬，我纯小白，交流起来让你费力了。

**Comment by yizhilangou** [comment]
> 哪个套壳网站？之前问你用的哪个前端，你就告诉我访问http://ip:8080/chatgpt/backend-api/conversation

![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/2b1f82dc-44d4-4889-aaf8-03084762a3ca)
![image](https://github.com/maxduke/go-chatgpt-api/assets/97778348/12b1b9be-40af-442d-aba2-d8dde2bffbb3)

**Comment by maxduke** [comment]
之前401那个问题是不是通过加入accessToken已经解决了？
这个500的错误 看看调用的是哪个模型？

**Comment by yizhilangou** [comment]
> 之前401那个问题是不是通过加入accessToken已经解决了？ 这个500的错误 看看调用的是哪个模型？

填accessToken默认就是3.5吧，我没开通plus.之前也是这样正常使用，昨天使用的时候就发现500了

**Comment by maxduke** [comment]
> > 之前401那个问题是不是通过加入accessToken已经解决了？ 这个500的错误 看看调用的是哪个模型？
> 
> 填accessToken默认就是3.5吧，我没开通plus.之前也是这样正常使用，昨天使用的时候就发现500了

参照 https://github.com/maxduke/go-chatgpt-api/issues/43

**Comment by yizhilangou** [comment]
> > > 之前401那个问题是不是通过加入accessToken已经解决了？ 这个500的错误 看看调用的是哪个模型？
> > 
> > 
> > 填accessToken默认就是3.5吧，我没开通plus.之前也是这样正常使用，昨天使用的时候就发现500了
> 
> 参照 #43

感谢大佬耐心回复，已经切换模型，现在正常运行。
