### ISSUE TITLE
想请问下大佬有计划把Refresh token 更换为 session token么？

### ISSUE THREAD

**Issue by xixi-furry** [maxduke/go-chatgpt-api#55]
RT，refresh token暂时好像没看到有路子可以取了，要是能换成session token就好了，也可以方便不用每几天更换一次了

**Comment by maxduke** [comment]
那个感觉不太稳。而且有个问题，用rt刷新拿到的access token可以稳定7-10天不过期。用session的那个话不好说。
最大的问题是没时间，而且我有rt，所以没什么动力改......之后有空再说吧。
关于获取 rt, 可以参考下
https://linux.do/t/topic/58580
