### ISSUE TITLE
gpts参数问题

### ISSUE THREAD

**Issue by devkeep163** [maxduke/go-chatgpt-api#57]
gpts貌似少了参数，如图下：
![348bfced1c0d199433774b1c4f38f0b](https://github.com/maxduke/go-chatgpt-api/assets/165616022/b564c4ce-e859-4972-8c0f-58be66a755ab)

**Comment by maxduke** [comment]
这个项目没支持gpts，因为我用的前端不支持gpts.....你用的什么前端？

**Comment by devkeep163** [comment]
> 这个项目没支持gpts，因为我用的前端不支持gpts.....你用的什么前端？

扒的官方的UI

**Comment by maxduke** [comment]
这些字段加了，能不能用不知道，目前只支持conversation接口
