### ISSUE TITLE
gpts问题，目前已测试修复，

### ISSUE THREAD

**Issue by devkeep163** [maxduke/go-chatgpt-api#60]
`typings.go文件如下：

type CreateConversationRequest struct {
	Action                     string    	`json:"action"`
	Messages                   []Message 	`json:"messages,omitempty"`
	Model                      string    	`json:"model"`
	ParentMessageID            string    	`json:"parent_message_id,omitempty"`
	ConversationID             string    	`json:"conversation_id,omitempty"`
	TimezoneOffsetMin          int       	`json:"timezone_offset_min"`
	ForceUseSse                bool      	`json:"force_use_sse"`
	HistoryAndTrainingDisabled bool      	`json:"history_and_training_disabled"`
	AutoContinue               bool      	`json:"auto_continue"`
	Suggestions                []string  	`json:"suggestions"`
	WebsocketRequestId         string    	`json:"websocket_request_id"`

       //  新增
	Conversation_mode          interface{}  `json:"conversation_mode,omitempty"`
	PluginIDs                  []string  	`json:"plugin_ids,omitempty"`
	PluginData                 interface{} 	`json:"plugin_data,omitempty"`
	Force_nulligen             bool      	`json:"force_nulligen,omitempty"`
	Force_paragen              bool      	`json:"force_paragen,omitempty"`
	Force_paragen_model_slug   string    	`json:"force_paragen_model_slug,omitempty"`
	Force_rate_limit           bool      	`json:"force_rate_limit,omitempty"`
}

type Author struct {
	Role string `json:"role"`

        //  新增
	Nane interface{} `json:"name,omitempty"` 
	Metadata interface{} `json:"metadata,omitempty"` 
}`

**Comment by devkeep163** [comment]
老哥空了可以同步下，几个参数都为非必填项，不影响原有逻辑，就几行代码，我就不PR了，测试已通过，辛苦

**Comment by maxduke** [comment]
昨晚改的还缺是么？
PluginIDs                  []string  	`json:"plugin_ids,omitempty"`
PluginData                 interface{} 	`json:"plugin_data,omitempty"`
这2个还需要？
之前被我删了

**Comment by devkeep163** [comment]
好像是搜索时需要

**Comment by maxduke** [comment]
给个你用的gpts我看一下

**Comment by huchenz1** [comment]
> 老哥空了可以同步下，几个参数都为非必填项，不影响原有逻辑，就几行代码，我就不PR了，测试已通过，辛苦

老哥请问你的前端可以分享一下吗 感谢！

**Comment by devkeep163** [comment]
> 可以同步下，几个参数都为非必填项，

使用潘多拉或者xyhelper的那个即可

**Comment by devkeep163** [comment]
> 给个你用的gpts我看一下

老哥怎么给你看，给你截参数吗？

**Comment by maxduke** [comment]
就是你用哪个GPTS涉及到plugin参数的？我去跑下

**Comment by devkeep163** [comment]
用webpilot

**Comment by maxduke** [comment]
> 用webpilot

跑了下，没看到Plugin相关的字段。
