### ISSUE TITLE
[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error

### ISSUE THREAD

**Issue by xionggd** [maxduke/go-chatgpt-api#63]
老哥，今天使用不了了； 看看啥原因了

![image](https://github.com/maxduke/go-chatgpt-api/assets/30542155/78b943ca-19d8-4590-8976-d921d4593529)

![image](https://github.com/maxduke/go-chatgpt-api/assets/30542155/791e15d7-6dcc-48bd-aa3b-2e9c1d40efda)

**Comment by maxduke** [comment]
看看你服务器网络能不能访问chatgpt

**Comment by xionggd** [comment]
> 看看你服务器网络能不能访问chatgpt

可以访问的； 我vpn代理过去直接访问官方网站的gpt也是没问题的。 我发现用不了 我还更新了 docker的最新镜像。

老哥，你那边有这个问题吗？

**Comment by maxduke** [comment]
我这边刚试了正常，有条件的话换个IP试一下

**Comment by xionggd** [comment]
> 我这边刚试了正常，有条件的话换个IP试一下

ip的确出现问题了； 那个ip使用的时候出现人机校验。
