### ISSUE TITLE
/backend-api/sentinel/chat-requirements 返沪格式html不是json

### ISSUE THREAD

**Issue by hardywu** [maxduke/go-chatgpt-api#67]
api.go 里的 CheckRequire函数
···go
err = json.NewDecoder(response.Body).Decode(&require)
···
response.Body is html格式，json 解析错误。

用了几天都正常，今天开始出错。

**Comment by maxduke** [comment]
> api.go 里的 CheckRequire函数 ···go err = json.NewDecoder(response.Body).Decode(&require) ··· response.Body is html格式，json 解析错误。
> 
> 用了几天都正常，今天开始出错。

刚试了没问了，看看ip是不是出盾了

**Comment by hardywu** [comment]
@maxduke 确实是。网络走了ipv6 （因为是ipv6 tunnel，所以被盾）...。我强制 /etc/hosts 固定ipv4 就好了。
