### ISSUE TITLE
a valid HAR file which contains gpt-4 arkose is required

### ISSUE THREAD

**Issue by xionggd** [maxduke/go-chatgpt-api#68]
![image](https://github.com/maxduke/go-chatgpt-api/assets/30542155/36583a37-5702-454d-b6b1-6fc96e492cd5)

大佬，今天不知道为何出现这种情况。问答成功率极低了。

**Comment by maxduke** [comment]
> ![image](https://private-user-images.githubusercontent.com/30542155/339787460-36583a37-5702-454d-b6b1-6fc96e492cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ4MDUsIm5iZiI6MTcxODM3NDUwNSwicGF0aCI6Ii8zMDU0MjE1NS8zMzk3ODc0NjAtMzY1ODNhMzctNTcwMi00NTRkLWI2YjEtNmZjOTZlNDkyY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmVhMTI0YjI5YTQ4OGY4ZDZiMTA0NWI2MGM3NTVhNDJhNDZjY2NkN2ZjM2ZlYzUzOWI0N2FkM2VmMWQ4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPGRx54cZR9SoX-8416NUWsmLp9JVtocBGY6FJ81uyU)
> 
> 大佬，今天不知道为何出现这种情况。问答成功率极低了。

看起来像HAR失效了，重新抓下试试

**Comment by xionggd** [comment]
> > ![image](https://private-user-images.githubusercontent.com/30542155/339787460-36583a37-5702-454d-b6b1-6fc96e492cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ4MDUsIm5iZiI6MTcxODM3NDUwNSwicGF0aCI6Ii8zMDU0MjE1NS8zMzk3ODc0NjAtMzY1ODNhMzctNTcwMi00NTRkLWI2YjEtNmZjOTZlNDkyY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmVhMTI0YjI5YTQ4OGY4ZDZiMTA0NWI2MGM3NTVhNDJhNDZjY2NkN2ZjM2ZlYzUzOWI0N2FkM2VmMWQ4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPGRx54cZR9SoX-8416NUWsmLp9JVtocBGY6FJ81uyU)
> > 大佬，今天不知道为何出现这种情况。问答成功率极低了。
> 
> 看起来像HAR失效了，重新抓下试试

尝试重新抓取过，当时不行， 给它晾了2天自然的好了。

**Comment by maxduke** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/30542155/339787460-36583a37-5702-454d-b6b1-6fc96e492cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ4MDUsIm5iZiI6MTcxODM3NDUwNSwicGF0aCI6Ii8zMDU0MjE1NS8zMzk3ODc0NjAtMzY1ODNhMzctNTcwMi00NTRkLWI2YjEtNmZjOTZlNDkyY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmVhMTI0YjI5YTQ4OGY4ZDZiMTA0NWI2MGM3NTVhNDJhNDZjY2NkN2ZjM2ZlYzUzOWI0N2FkM2VmMWQ4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPGRx54cZR9SoX-8416NUWsmLp9JVtocBGY6FJ81uyU)
> > > 大佬，今天不知道为何出现这种情况。问答成功率极低了。
> > 
> > 
> > 看起来像HAR失效了，重新抓下试试
> 
> 尝试重新抓取过，当时不行， 给它晾了2天自然的好了。

那比较奇怪，听说有些号根本不需要arkose，可以去官网chat_requirments那个接口，看下返回的内容

**Comment by xionggd** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/30542155/339787460-36583a37-5702-454d-b6b1-6fc96e492cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ4MDUsIm5iZiI6MTcxODM3NDUwNSwicGF0aCI6Ii8zMDU0MjE1NS8zMzk3ODc0NjAtMzY1ODNhMzctNTcwMi00NTRkLWI2YjEtNmZjOTZlNDkyY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmVhMTI0YjI5YTQ4OGY4ZDZiMTA0NWI2MGM3NTVhNDJhNDZjY2NkN2ZjM2ZlYzUzOWI0N2FkM2VmMWQ4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPGRx54cZR9SoX-8416NUWsmLp9JVtocBGY6FJ81uyU)
> > > > 大佬，今天不知道为何出现这种情况。问答成功率极低了。
> > > 
> > > 
> > > 看起来像HAR失效了，重新抓下试试
> > 
> > 
> > 尝试重新抓取过，当时不行， 给它晾了2天自然的好了。
> 
> 那比较奇怪，听说有些号根本不需要arkose，可以去官网chat_requirments那个接口，看下返回的内容

![image](https://github.com/maxduke/go-chatgpt-api/assets/30542155/e853ecf6-10a5-4e59-8952-0a6290bfff45)
数据看不懂。

**Comment by maxduke** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/30542155/339787460-36583a37-5702-454d-b6b1-6fc96e492cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ4MDUsIm5iZiI6MTcxODM3NDUwNSwicGF0aCI6Ii8zMDU0MjE1NS8zMzk3ODc0NjAtMzY1ODNhMzctNTcwMi00NTRkLWI2YjEtNmZjOTZlNDkyY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmVhMTI0YjI5YTQ4OGY4ZDZiMTA0NWI2MGM3NTVhNDJhNDZjY2NkN2ZjM2ZlYzUzOWI0N2FkM2VmMWQ4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPGRx54cZR9SoX-8416NUWsmLp9JVtocBGY6FJ81uyU)
> > > > > 大佬，今天不知道为何出现这种情况。问答成功率极低了。
> > > > 
> > > > 
> > > > 看起来像HAR失效了，重新抓下试试
> > > 
> > > 
> > > 尝试重新抓取过，当时不行， 给它晾了2天自然的好了。
> > 
> > 
> > 那比较奇怪，听说有些号根本不需要arkose，可以去官网chat_requirments那个接口，看下返回的内容
> 
> ![image](https://private-user-images.githubusercontent.com/30542155/340201400-e853ecf6-10a5-4e59-8952-0a6290bfff45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDY5MjIsIm5iZiI6MTcxODYwNjYyMiwicGF0aCI6Ii8zMDU0MjE1NS8zNDAyMDE0MDAtZTg1M2VjZjYtMTBhNS00ZTU5LTg5NTItMGE2MjkwYmZmZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyM2JmNDZjYzdhYzhiYmJlODlkY2IyMzQwMGRlODQwMDVmM2M1ZmUyNDM4OTcyMGMyMWU1MTA2YjVmNDhmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Coj_RHz9MvN70HhNAuoZBKTyWllfSIsAKIE_lKRJYdM) 数据看不懂。

果真你的账号加IP不需要 arkose打码。 你前几天报错是突然需要打码了，估计你HAR没抓好，或者没放对位置

**Comment by xionggd** [comment]
> > > > > > ![image](https://private-user-images.githubusercontent.com/30542155/339787460-36583a37-5702-454d-b6b1-6fc96e492cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ4MDUsIm5iZiI6MTcxODM3NDUwNSwicGF0aCI6Ii8zMDU0MjE1NS8zMzk3ODc0NjAtMzY1ODNhMzctNTcwMi00NTRkLWI2YjEtNmZjOTZlNDkyY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmVhMTI0YjI5YTQ4OGY4ZDZiMTA0NWI2MGM3NTVhNDJhNDZjY2NkN2ZjM2ZlYzUzOWI0N2FkM2VmMWQ4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPGRx54cZR9SoX-8416NUWsmLp9JVtocBGY6FJ81uyU)
> > > > > > 大佬，今天不知道为何出现这种情况。问答成功率极低了。
> > > > > 
> > > > > 
> > > > > 看起来像HAR失效了，重新抓下试试
> > > > 
> > > > 
> > > > 尝试重新抓取过，当时不行， 给它晾了2天自然的好了。
> > > 
> > > 
> > > 那比较奇怪，听说有些号根本不需要arkose，可以去官网chat_requirments那个接口，看下返回的内容
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/30542155/340201400-e853ecf6-10a5-4e59-8952-0a6290bfff45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDY5MjIsIm5iZiI6MTcxODYwNjYyMiwicGF0aCI6Ii8zMDU0MjE1NS8zNDAyMDE0MDAtZTg1M2VjZjYtMTBhNS00ZTU5LTg5NTItMGE2MjkwYmZmZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyM2JmNDZjYzdhYzhiYmJlODlkY2IyMzQwMGRlODQwMDVmM2M1ZmUyNDM4OTcyMGMyMWU1MTA2YjVmNDhmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Coj_RHz9MvN70HhNAuoZBKTyWllfSIsAKIE_lKRJYdM) 数据看不懂。
> 
> 果真你的账号加IP不需要 arkose打码。 你前几天报错是突然需要打码了，估计你HAR没抓好，或者没放对位置

搞不懂，我按照教程反复抓取了，  har 我映射到宿主机 但是没给 777 最高权限，不清楚会不会影响到。

**Comment by maxduke** [comment]
你看看后台log，有没有读取到HAR文件
正常读到的话会提示
go-chatgpt-api  | success read chat arkose

**Comment by xionggd** [comment]
> 你看看后台log，有没有读取到HAR文件 正常读到的话会提示 go-chatgpt-api | success read chat arkose

![image](https://github.com/maxduke/go-chatgpt-api/assets/30542155/c08a240f-51db-45e1-a597-901b1c359cad)
这是3天前的一个日志。 看日志应该是读取到了的

**Comment by maxduke** [comment]
没看到有读到"chat" arkose

**Comment by xionggd** [comment]
> 没看到有读到"chat" arkose

docker run -d --name go-chatgpt-api \
-p 7999:8080  \
--network=my-net \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
-v /home/harPool:/app/harPool \
-e TZ=Asia/Shanghai \
-e PROXY= \
-e ARKOSE_TOKEN_URL= \
-e BX= \
-e BX_URL= \
-e OPENAI_EMAIL= \
-e OPENAI_PASSWORD= \
-e CONTINUE_SIGNAL= \
--restart unless-stopped \
maxduke/go-chatgpt-api

难道我配置有问题吗？ 大佬帮看看

**Comment by maxduke** [comment]
抓到的har文件放你本地的/home/harPool里
空的环境变量都删了吧

**Comment by xionggd** [comment]
> 抓到的har文件放你本地的/home/harPool里 空的环境变量都删了吧

![image](https://github.com/maxduke/go-chatgpt-api/assets/30542155/a83b3f4a-71dc-45c6-bfff-6e9e5cd953af)
是按照这个方法抓取没错吧？

**Comment by maxduke** [comment]
对，问题是，如果你账号在不出arkose的时候可能抓不到......
你看看有抓到图中的请求么
![image](https://github.com/maxduke/go-chatgpt-api/assets/440836/4f5b93e1-7e01-450d-ba83-f8522c4e8dc3)

**Comment by xionggd** [comment]
> 对，问题是，如果你账号在不出arkose的时候可能抓不到...... 你看看有抓到图中的请求么 ![image](https://private-user-images.githubusercontent.com/440836/340236476-4f5b93e1-7e01-450d-ba83-f8522c4e8dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTQzMTMsIm5iZiI6MTcxODYxNDAxMywicGF0aCI6Ii80NDA4MzYvMzQwMjM2NDc2LTRmNWI5M2UxLTdlMDEtNDUwZC1iYTgzLWY4NTIyYzRlOGRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwODQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDMxMzc5ZmIwNzJkNjliZWE2NGMwOGUzN2I2ZjcxZWI2Mzk1MGM2Mjk5Njc3NWM0YTBjNTUxN2FmMDRlNWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oYXS6gbzgxmVu80xiE7y-LyOQiN4VyKAUNj5UPJtENE)

没有这种请求。 等再出现情况我再看看 再去抓取试试吧。谢谢大佬啦
