### ISSUE TITLE
搭建教程(大佬您好，我问一下看起来有点蠢的问题)

### ISSUE THREAD

**Issue by liujingyangself** [maxduke/go-chatgpt-api#69]
大佬您好，我问一下看起来有点蠢的问题，请问您这个项目如何搭建，有没有可以参考的教程。我试了很多次，您看这个yml写的对嘛
version: '3.8'  # 根据您的Docker版本选择合适的Compose文件版本

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: ghcr.io/maxduke/go-chatgpt-api:latest  # 修改为从GitHub Container Registry拉取的镜像
    ports:
      - "8080:8080"  # 宿主机8080端口映射到容器的8080端口
    environment:
      - GIN_MODE=release
      - GO_chatgpt_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: maxduke/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped

**Comment by maxduke** [comment]
一直懒得改写最新的配置，网上帮你找了教程 https://elmagnifico.tech/2023/12/22/CWS/
maxduke/chatgpt-proxy-server-warp 这个镜像是没的，用代理的话，用环境变量 PROXY

**Comment by liujingyangself** [comment]
> 一直懒得改写最新的配置，网上帮你找了教程 https://elmagnifico.tech/2023/12/22/CWS/ maxduke/chatgpt-proxy-server-warp 这个镜像是没的，用代理的话，用环境变量 PROXY

感谢大佬，以前看到过这个帖子，不知道他部署的竟然就是您的。再次表达谢意。

**Comment by liujingyangself** [comment]
https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147
但是前一阵儿我发现har好像拿不到了，以前用这个连接就能搜到，现在好像搜不到了。

**Comment by maxduke** [comment]
你的是普号是么？大概率不用arkose打码了

**Comment by liujingyangself** [comment]
我是自己的号，就是想给家人用一下。我用这个方法拿到har了，但是，用cws可以拿到历史会话，但是给gpt提问题的时候会报这个错误
OpenAI 授权失败 (403 错误)，请联系管理员处理 OpenaiWebException: [403] errors.openaiWeb {"errorMessage":"a valid HAR file which contains gpt-4 arkose is required"}

以下是我取的har的方法
HAR文件池
当前登录账号，使用GPT-4模型以及大部分GPT-3.5模型，均需要配置HAR文件（.har后缀名的文件）以完成captcha验证。
使用基于chromium的浏览器（Chrome，Edge）打开浏览器开发者工具（F12），并切换到网络标签页，勾选保留日志选项。
登录https://chatgpt.com/，新建聊天并选择GPT-4模型，随意输入下文字，切换到GPT-3.5模型，随意输入下文字。
点击网络标签页下的导出HAR按钮，导出文件chatgpt.com.har，放置到本程序同级的harPool文件夹里。

**Comment by maxduke** [comment]
参照下 https://github.com/maxduke/go-chatgpt-api/issues/68

**Comment by liujingyangself** [comment]
> https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147
> 但是前一阵儿我发现har好像拿不到了，以前用这个连接就能搜到，现在好像搜不到了。

那中枪了，我就没有这个玩意，哈哈哈，晾几天吧，或者我换个电脑试试

**Comment by maxduke** [comment]
那按理说就不会触发那个错误，镜像更新到最新试试

**Comment by liujingyangself** [comment]
我拉取的都是最新的，难道跟时区还有关系，我是在日本
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=${TZ}
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: ghcr.io/maxduke/go-chatgpt-api:latest
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - PORT=
      - TZ=Asia/Shanghai
      - PROXY=
      - OPENAI_EMAIL=
      - OPENAI_PASSWORD=
      - CONTINUE_SIGNAL=
      - ENABLE_HISTORY=
      - IMITATE_ACCESS_TOKEN=
    volumes:
      - ./harPool:/app/harPool
    restart: unless-stopped

**Comment by maxduke** [comment]
把空的环境变量都删了
话说chat-requirments接口中没有arkose要求的话，对话应该就不需要靠har打码

**Comment by liujingyangself** [comment]
> 把空的环境变量都删了 话说chat-requirments接口中没有arkose要求的话，对话应该就不需要靠har打码
我用这个再拉取一次，我把时区改成东京试试。
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=${TZ}
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: ghcr.io/maxduke/go-chatgpt-api:latest
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - TZ=Asia/${TZ}
    volumes:
      - ./harPool:/app/harPool
    restart: unless-stopped

**Comment by liujingyangself** [comment]
空参数都删了，我又换了一台电脑登录了一次，拿下来har，最后还是403，显示的就是读不到har
ERROR: [cws.api.routers.chat] <OpenaiWebException> OpenaiWebException: [403] errors.openaiWeb {"errorMessage":"a valid HAR file which contains gpt-4 arkose is required"}

**Comment by maxduke** [comment]
还是参考之前那个issue ， 确保去官网抓har的ip 和，之后使用的IP一致

**Comment by liujingyangself** [comment]
> 还是参考之前那个issue ， 确保去官网抓har的ip 和，之后使用的IP一致
一样的，服务器ubuntu是我家内网的地址，服务器是虚拟机，访问地址也是在我家的windows浏览器。

**Comment by maxduke** [comment]
看下官网chat-requirments接口的返回

**Comment by liujingyangself** [comment]
![捕获](https://github.com/maxduke/go-chatgpt-api/assets/52322795/e75f727a-e2fc-477c-bed4-9cea8cb24271)

**Comment by maxduke** [comment]
设置个环境变量UA为你浏览器的useragent，配置的时候不要引号。直接=

**Comment by liujingyangself** [comment]
这样配置是嘛
go-chatgpt-api:
container_name: go-chatgpt-api
image: ghcr.io/maxduke/go-chatgpt-api:latest
ports:
- 127.0.0.1:8080:8080
environment:
- TZ=Asia/${TZ}
- UA=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
volumes:
- ./harPool:/app/harPool
restart: unless-stopped

**Comment by liujingyangself** [comment]
大佬牛逼，就是header的useragent问题。

**Comment by liujingyangself** [comment]
![微信图片_20240621215425](https://github.com/maxduke/go-chatgpt-api/assets/52322795/a1d36e5c-e81e-4aad-89bf-a461e9bbebac)
但是，这种办法布置到vps上就不行了吧。我现在用了一台nerdvm的vps，发现访问不了。我换成搬瓦工试试。

**Comment by maxduke** [comment]
对IP的干净程度有要求

**Comment by liujingyangself** [comment]
![微信截图_20240621220842](https://github.com/maxduke/go-chatgpt-api/assets/52322795/1876235b-deb7-4576-bbc2-3fa3cff59b6c)
这个可能就是为了IP纯净度做的修改。但是现在没办法用了。

**Comment by maxduke** [comment]
没办法，大众用的多的VPS IP大多都不行，自己找代理，然后用环境变量PROXY

**Comment by liujingyangself** [comment]
> 没办法，大众用的多的VPS IP大多都不行，自己找代理，然后用环境变量PROXY

感谢大佬，耽误您这么长时间，我找下代理，实在不行我就开一台电脑，自己弄个代理，哈哈哈。

**Comment by liujingyangself** [comment]
![sile](https://github.com/maxduke/go-chatgpt-api/assets/52322795/67f19d07-3c37-43bc-a14a-eaf694c88065)
我用了一个甲骨文云，IP倒是干净能访问了，但是立马403死给我看，哈哈哈。

**Comment by maxduke** [comment]
> ![sile](https://private-user-images.githubusercontent.com/52322795/341778673-67f19d07-3c37-43bc-a14a-eaf694c88065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Nzc3MjcsIm5iZiI6MTcxODk3NzQyNywicGF0aCI6Ii81MjMyMjc5NS8zNDE3Nzg2NzMtNjdmMTlkMDctM2MzNy00M2JjLWExNGEtZWFmNjk0Yzg4MDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEzNDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzc3NTk3N2FkNDlmN2I5MmE2YTVjMDNiOTkyMTAxNGM5ZTViNTNlYWIzMjZkOTk5NTI3MmIxMmJiNGQxMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A8wS1ZTKbRYx5C5vldGyxr9I4PD4xpEepAKeTIAO8js) 我用了一个甲骨文云，IP倒是干净能访问了，但是立马403死给我看，哈哈哈。

你挂甲骨文那个IP去官方抓har

**Comment by liujingyangself** [comment]
> > ![sile](https://private-user-images.githubusercontent.com/52322795/341778673-67f19d07-3c37-43bc-a14a-eaf694c88065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Nzc3MjcsIm5iZiI6MTcxODk3NzQyNywicGF0aCI6Ii81MjMyMjc5NS8zNDE3Nzg2NzMtNjdmMTlkMDctM2MzNy00M2JjLWExNGEtZWFmNjk0Yzg4MDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEzNDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzc3NTk3N2FkNDlmN2I5MmE2YTVjMDNiOTkyMTAxNGM5ZTViNTNlYWIzMjZkOTk5NTI3MmIxMmJiNGQxMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A8wS1ZTKbRYx5C5vldGyxr9I4PD4xpEepAKeTIAO8js) 我用了一个甲骨文云，IP倒是干净能访问了，但是立马403死给我看，哈哈哈。
> 
> 
> 
> 你挂甲骨文那个IP去官方抓har

大佬就是大佬，一下点醒我了
