### ISSUE TITLE
提示500，报错日志已提供

### ISSUE THREAD

**Issue by xixi-furry** [maxduke/go-chatgpt-api#75]
[GIN] 2024/09/02 - 09:42:29 | 500 |  1.772591421s |      172.19.0.4 | POST     "/chatgpt/backend-api/conversation"

2024/09/02 09:42:29 [Recovery] 2024/09/02 - 09:42:29 panic recovered:
interface conversion: interface {} is nil, not chatgpt.FuncType
/usr/local/go/src/runtime/iface.go:262 (0x40b944)
/app/api/chatgpt/turnstile.go:400 (0x994037)
/app/api/chatgpt/api.go:414 (0x989087)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x90c02a)
/app/middleware/cors.go:19 (0x9a3905)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x911c79)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 (0x911c67)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x910da4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 (0x910d8b)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x910191)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0x90fc00)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0x90f731)
/usr/local/go/src/net/http/server.go:3142 (0x6dd78d)
/usr/local/go/src/net/http/server.go:2044 (0x6d9d67)
/usr/local/go/src/runtime/asm_amd64.s:1695 (0x46d760)

**Comment by maxduke** [comment]
暂时把环境变量去了 PROCESS_TURNSTILE

**Comment by xixi-furry** [comment]
关掉了正常了，谢谢老大
