### ISSUE TITLE
unable to check chat requirement

### ISSUE THREAD

**Issue by mr-inly** [maxduke/go-chatgpt-api#76]
max大佬，你好，用了你的镜像，从7月到现在一直稳定非常好用，大概9月2或3号开始出现问题，报错就只有下面这一句
ERRO[0597] unable to check chat requirement                                                                       
[GIN] 2024/09/10 - 23:10:41 | 200 |  918.136949ms |      172.17.0.1 | POST     "/chatgpt/backend-api/conversation"

我是用群晖的docker中拉取了最新的镜像，然后执行docker run -d --name go-chatgpt-api -p 7989:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api 拉起来的。
web端用的是chenzhaoyu94/chatgpt-web的镜像，ACCESS_TOKEN自己写了个脚本会定期更新，OPENAI_API_MODEL传的是text-davinci-002-render-sha

有空帮忙看看啥问题，需要什么信息，可以再提供。

**Comment by maxduke** [comment]
> max大佬，你好，用了你的镜像，从7月到现在一直稳定非常好用，大概9月2或3号开始出现问题，报错就只有下面这一句 ERRO[0597] unable to check chat requirement [GIN] 2024/09/10 - 23:10:41 | 200 | 918.136949ms | 172.17.0.1 | POST "/chatgpt/backend-api/conversation"
> 
> 我是用群晖的docker中拉取了最新的镜像，然后执行docker run -d --name go-chatgpt-api -p 7989:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -e TZ=Asia/Shanghai -e PROXY= -e ARKOSE_TOKEN_URL= -e BX= -e BX_URL= -e OPENAI_EMAIL= -e OPENAI_PASSWORD= -e CONTINUE_SIGNAL= --restart unless-stopped maxduke/go-chatgpt-api 拉起来的。 web端用的是chenzhaoyu94/chatgpt-web的镜像，ACCESS_TOKEN自己写了个脚本会定期更新，OPENAI_API_MODEL传的是text-davinci-002-render-sha
> 
> 有空帮忙看看啥问题，需要什么信息，可以再提供。

感觉是access token实效了，或者ip 问题，或者UA问题。  先验证下access token有效性，还不行就环境变量换个UA。 然后，其实你启动时候空的环境变量不需要设置，其次自己没用那个前端，但text-davinci-002-render-sha 应该是之前的3.5吧，官网都去掉了，普号推荐替换为gpt-4o-mini，不然逆向太明显了。

**Comment by mr-inly** [comment]
很高興收到你的電子郵件。Glad to receive your E-mail.あなたの電子メールを受け取って非常に嬉しい。                                                         --inly

**Comment by mr-inly** [comment]
很高興收到你的電子郵件。Glad to receive your E-mail.あなたの電子メールを受け取って非常に嬉しい。                                                         --inly

**Comment by mr-inly** [comment]
很高興收到你的電子郵件。Glad to receive your E-mail.あなたの電子メールを受け取って非常に嬉しい。                                                         --inly
