### ISSUE TITLE
卡在 valid HAR file which contains login arkose is require了

### ISSUE THREAD

**Issue by mar-heaven** [maxduke/go-chatgpt-api#77]
我是想用email,password登录获取refresh_token的，目前卡在这一步了，想知道如果只是获取refresh_token下一步要走arkose这一步吗？因为时间比较急，所以如果可能的话希望有偿帮忙看看，谢谢！

**Comment by maxduke** [comment]
1 登录接口是用来取access token, 不支持取rt
2 登录接口风控很高，很久没维护了

**Comment by mar-heaven** [comment]
请问有什么办法可以通过账号密码获取rt吗，还是说可以通过access token 获取rt

**Comment by maxduke** [comment]
https://linux.do/t/topic/226241
